version: '3.5'
services:

  api_app:
    image: git_inspect_api_app
    container_name: git_inspect_api_app
    env_file:
      - api/.env
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - git_inspect
    ports:
      - 9084:9084
      - 3084:3084
    restart: always
    depends_on:
      - api_nginx
  api_nginx:
    image: git_inspect_api_nginx
    container_name: git_inspect_api_nginx
    build:
      context: api
      dockerfile: Dockerfile.nginx
    networks:
      - git_inspect
    ports:
      - 8084:8084
    restart: always

  client:
    image: git_inspect_client
    container_name: git_inspect_client
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - git_inspect
    ports:
      - 8085:8085
    restart: always

networks:
  git_inspect:
    name: git_inspect
    driver: bridge
